MAIN = main.cpp
TEMP = tempTracker.cpp


CC = g++
STD = -std=c++11
DEBUG = -g
CFLAGS = -Wall -c $(DEBUG)
LFLAGS = -Wall $(DEBUG)


p1 : 
	$(CC) $(STD) $(LFLAGS) $(MAIN) $(TEMP) -o p1

temp:
	$(CC) $(STD) $(LFLAGS) $(TEMP)

clean:
	\rm  p1	
