OBJS = main.cpp
LIST = listNode.cpp 
FUNCT = functions.cpp
CC = g++
STD = -std=c++11
DEBUG = -g
CFLAGS = -Wall -c $(DEBUG)
LFLAGS = -Wall $(DEBUG)


p1 : 
	$(CC) $(STD) $(LFLAGS) $(LIST) $(OBJS) 

funct : 
	$(CC) $(STD) $(LFLAGS) $(FUNCT)

list : 
	$(CC) $(STD) $(LFLAGS) $(LIST)

clean:
	\rm a.out	
