OBJS = main.cpp
STACK = maxStack.cpp 
CC = g++
STD = -std=c++11
DEBUG = -g
CFLAGS = -Wall -c $(DEBUG)
LFLAGS = -Wall $(DEBUG)


p1 : 
	$(CC) $(STD) $(LFLAGS) $(STACK)  $(OBJS) 


stack : 
	$(CC) $(STD) $(LFLAGS) $(STACK)

clean:
	\rm a.out	
